name: flutter_view_modifiers
# description: "Swift way of Writing flutter code"
description: 
  "A Flutter package that enhances widget flexibility with powerful extension methods. 
  Effortlessly chain modifiers like padding, margin, alignment, decoration, and more 
  for cleaner, readable, and maintainable code. Simplify your UI development with 
  expressive and reusable modifiers."

version: 0.0.6
homepage: https://github.com/quickcodes/flutter_view_modifiers

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
